version: '3.8'
services:
  db: # if you want run db
    env_file:
      - .env
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
    networks:
      - my-network
  go-application:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .Dockerfile # path to your dockerfile
    environment: # set your env variables
      SERVER_ADDR: ${SERVER_ADDR}
      DB_DSN: ${DB_DSN}
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my-network


networks:
  my-network: